import type { Candidature } from "./types";

export function uid(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

/** Données de démo — ids régénérés à chaque appel (premier chargement base vide). */
export function buildSampleData(): Candidature[] {
  return [
    {
      id: uid(),
      company: "Doctolib",
      job_title: "Frontend Developer",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "hybride",
      source: "LinkedIn",
      job_url: "https://doctolib.fr/jobs",
      date_found: "2026-03-10",
      date_applied: "2026-03-12",
      status: "entretien rh",
      priority: "haute",
      salary: "50k–60k",
      contact_name: "Marie Dupont",
      contact_email: "marie@doctolib.fr",
      follow_up_date: "2026-03-25",
      notes:
        "React TypeScript, produit SaaS médical. Entretien prévu le 22/03.",
      _createdAt: "2026-03-12T09:00:00.000Z",
    },
    {
      id: uid(),
      company: "Pennylane",
      job_title: "UX Designer",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "remote",
      source: "Welcome to the Jungle",
      job_url: "",
      date_found: "2026-03-15",
      date_applied: "2026-03-16",
      status: "envoyée",
      priority: "haute",
      salary: "45k–52k",
      contact_name: "",
      contact_email: "",
      follow_up_date: "2026-03-26",
      notes: "Stack Figma, Design System. Produit fintech B2B.",
      _createdAt: "2026-03-16T10:00:00.000Z",
    },
    {
      id: uid(),
      company: "BlaBlaCar",
      job_title: "Lead Front-End",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "hybride",
      source: "site carrière",
      job_url: "https://blablacar.com/careers",
      date_found: "2026-03-18",
      date_applied: "",
      status: "à envoyer",
      priority: "moyenne",
      salary: "",
      contact_name: "",
      contact_email: "",
      follow_up_date: "",
      notes: "Vue 3 + Nuxt. Niveau Lead requis.",
      _createdAt: "2026-03-18T14:00:00.000Z",
    },
    {
      id: uid(),
      company: "Contentsquare",
      job_title: "Software Engineer Front",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "hybride",
      source: "LinkedIn",
      job_url: "",
      date_found: "2026-03-20",
      date_applied: "2026-03-21",
      status: "test technique",
      priority: "haute",
      salary: "55k–65k",
      contact_name: "Paul Renard",
      contact_email: "p.renard@cs.com",
      follow_up_date: "2026-04-01",
      notes: "Angular ou React. Test: kata en 4h.",
      _createdAt: "2026-03-21T08:00:00.000Z",
    },
    {
      id: uid(),
      company: "Leboncoin",
      job_title: "Développeur React",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "présentiel",
      source: "Indeed",
      job_url: "",
      date_found: "2026-03-22",
      date_applied: "2026-03-23",
      status: "refusée",
      priority: "basse",
      salary: "42k–48k",
      contact_name: "",
      contact_email: "",
      follow_up_date: "",
      notes: "Réponse négative reçue le 25/03. Pas de feedback.",
      _createdAt: "2026-03-23T09:00:00.000Z",
    },
    {
      id: uid(),
      company: "Backmarket",
      job_title: "Frontend Engineer",
      contract_type: "CDI",
      location: "Paris",
      work_mode: "hybride",
      source: "candidature spontanée",
      job_url: "",
      date_found: "2026-03-24",
      date_applied: "2026-03-24",
      status: "relance à faire",
      priority: "moyenne",
      salary: "50k–58k",
      contact_name: "",
      contact_email: "",
      follow_up_date: "2026-03-31",
      notes:
        "React + TypeScript. Équipe produit. Envoyer relance fin mars.",
      _createdAt: "2026-03-24T11:00:00.000Z",
    },
    {
      id: uid(),
      company: "Mirakl",
      job_title: "Intégrateur Web Freelance",
      contract_type: "freelance",
      location: "Remote",
      work_mode: "remote",
      source: "LinkedIn",
      job_url: "",
      date_found: "2026-03-26",
      date_applied: "2026-03-27",
      status: "en attente",
      priority: "moyenne",
      salary: "500 €/j",
      contact_name: "Alice Moreau",
      contact_email: "a.moreau@mirakl.com",
      follow_up_date: "2026-04-03",
      notes: "Mission 3 mois renouvelable. Full remote.",
      _createdAt: "2026-03-27T09:00:00.000Z",
    },
  ];
}
